### PR TITLE
fix verify-codegen

### LINKED ISSUE #694: `make verify` is broken
### Report

`make verify` is not detecting differences in generated code as it should. Currently, the code on the master branch is out of sync and `make verify` succeeds anyway.

### Expected Behavior

`make verify` should fail because the generated code is outdated.

### Actual Behavior

`make verify` succeeds.

### Steps to Reproduce the Problem

1. Run `make verify` on commit a47e91f.

### Logs from KEDA HTTP operator

_No response_

### What version of the KEDA HTTP Add-on are you running?

_No response_

### Kubernetes Version

None

### Platform

None

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by t0rr3sp3dr0**
Fix `verify-codegen.sh` and run `make codegen` to resync generated code.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] Any necessary documentation is added, such as:
  - [`README.md`](/README.md)
  - [The `docs/` directory](./docs)
  - [The docs repo](https://github.com/kedacore/keda-docs)

Fixes #694

### CODE REVIEW

**Comment by t0rr3sp3dr0** [comment]
@JorTurFer, it seems this was broken for a while. When we introduced multi-host support, the generated code became outdated but all the tests passed.

**Review by JorTurFer — APPROVED** [review]

**Comment by JorTurFer** [comment]
> @JorTurFer, it seems this was broken for a while. When we introduced multi-host support, the generated code became outdated but all the tests passed.

Lol... Interesting because I added an e2e test which tests multi-host use case and it works

**Comment by JorTurFer** [comment]
This is the test : https://github.com/kedacore/http-add-on/tree/main/tests%2Fchecks%2Fmultiple_hosts

**Comment by JorTurFer** [comment]
Tomorrow I'll check it but could the generated code have not changed? Now with your fix the generated code hasn't changed

**Comment by t0rr3sp3dr0** [comment]
It was just the check that was broken, `make generate` was producing the correct code. But if someone forgot to run it after changing the API structs, `make verify` would always succeed. 

The only part that was actually outdated is the DeepCopy implementation for HTTPScaledObjectSpec. This is not used by the code on the main branch, that's why the E2E tests succeeded. But it affected the new routing table implementation as it relies on that method, that's why I noticed the problem.

**Pull request merged**
