### PR TITLE
Documenting the targetPendingRequests field

### LINKED ISSUE #230: Documentation for target metric
After #168, we should add documentation for how and why to set the `targetPendingRequests` config parameter.

### PR DESCRIPTION
**Pull request by arschles**
Adding reference documentation for the `targetPendingRequests` field, which was added in #223

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] Any necessary documentation is added, such as:
  - [`README.md`](/README.md)
  - [The `docs/` directory](./docs)
  - [The docs repo](https://github.com/kedacore/keda-docs)

Fixes #230

### CODE REVIEW

**Comment by arschles** [comment]
cc/ @ajanth97

**Review by JorTurFer — APPROVED** [review]

**Review by tomkerkhove — COMMENTED** [review]
This section is very tech-focussed while with KEDA we typically aim to make it dead simple.

I would suggest to move this more into a design section and focus on what end-users have to know.

**Comment by arschles** [comment]
@tomkerkhove good point. I moved the technical stuff into the design doc as you suggested.

**Comment by arschles** [comment]
@tomkerkhove can you PTAL at this again?

**Review by tomkerkhove — APPROVED** [review]

**Pull request merged**
