### PR TITLE
Don't override Host when forward-proxying - effectively preserving the transparent proxy approach

### LINKED ISSUE #331: Proxy redirection to the wrong URL
Interceptor redirect to `http://service:80/path` instead of `http://url.com/path`

## Expected Behavior

Redirect to `http://url.com/path`

## Actual Behavior

Redirect from `http://url.com`to `http://service:80/path`

## Steps to Reproduce the Problem

  1. Create service and a deployment with HTTPScaledObject (in my case it was WordPress)
  2. Create an Ingress
  3. Go to the url (`http://example.com`) and it will redirect to `http://service:80`

## Specifications

- **KEDA Version:** v2.4.0
- **KEDA HTTP Add-on Version:** v0.2.0
- **Platform & Version:** M1 version v1.22.4
- **Kubernetes Version:** v1.21.5-gke.1802

A way to fix it would be to specify the correct host on the forwardRequest function instead of giving the service host. I don't really get why you don't use the host instead of the service url? ([here](https://github.com/kedacore/http-add-on/blob/main/interceptor/request_forwarder.go#L19))

We are basically setting fake host, so that's why WordPress is not able to redirect correctly. As a workaround, we use `HTTP_X_FORWARDED_HOST` header to get the correct host.

### PR DESCRIPTION
**Pull request by similark**
_Provide a description of what has been changed_
This small change solves #331 - when building the forward proxy request, there's no need to override the Host field, which trashes the Host header altogether. The request has the proper value in the URL, making it reach the target svc and still preserving the original Host. This makes it possible to treat the request properly down the road (at the application level)

### Checklist

- [X] Commits are signed with Developer Certificate of Origin (DCO)
- [ ] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [ ] Any necessary documentation is added, such as:
  - [`README.md`](/README.md)
  - [The `docs/` directory](./docs)
  - [The docs repo](https://github.com/kedacore/keda-docs)

Fixes #331

### CODE REVIEW

**Comment by similark** [comment]
Opinions, anyone? @JorTurFer

**Comment by JorTurFer** [comment]
is this correct @t0rr3sp3dr0 ?

**Comment by similark** [comment]
Just making note that this change is covered in the `TestImmediatelySuccessfulProxy` test.. meaning the request reaches its target as expected. Only difference is that now the Host header is kept as it was, and not updated. In a running cluster, the target pod will get the request with the actual Host in place, and not `service_name.svc.NAMESPACE.....`

**Comment by t0rr3sp3dr0** [comment]
I would do something like this:
```golang
	superDirector := proxy.Director
	proxy.Director = func(req *http.Request) {
		host := req.URL.Host
		superDirector(req)
		req.URL.Host = host

		// Strip client-provided forwarding headers to prevent IP spoofing.
		req.Header.Del("Forwarded")
		req.Header.Del("X-Forwarded-For")
		req.Header.Del("X-Forwarded-Host")
		req.Header.Del("X-Forwarded-Proto")
	}
```

**Comment by similark** [comment]
@t0rr3sp3dr0 how about this?

**Comment by similark** [comment]
Opinions, anyone? @tomkerkhove @JorTurFer @t0rr3sp3dr0 
This is kind of a show-stopper for us, as any downstream application can't figure the original request.

**Comment by t0rr3sp3dr0** [comment]
@similark, I’m ok with the changes, but you need to rebase your branch. The file you patched moved to `interceptor/handler/upstream.go`.

**Comment by t0rr3sp3dr0** [comment]
Also, update `CHANGELOG.md` to reflect this change.

**Pull request closed without merging**
