### PR TITLE
Refactoring the interceptor

### LINKED ISSUE #61: Interceptor doesn't always "hold" request when there are no replicas available
When there's no app available, we shouldn't get a connection refused. The request should hang until the app scales up from 0 to 1. Sometimes the interceptor doesn't do this.

We should also expose a timeout to the user via the `HTTPScaledObject` so that they can configure how long they'd like the interceptor to hold the request

### PR DESCRIPTION
**Pull request by arschles**
This PR fixes a bug in the interceptor in which it would not wait for a connection to be established if there was no server already waiting to accept conns, by adding a retry mechanism for the `DialContext` function in the HTTP proxy.

It does a few more things:

- Adding more testing to the proxy
- Refactoring the proxy to use standard net/http (gives it more control over the response lifecycle)
- Using the standard library test framework, because [stretchr/testify/suite](https://godoc.org/github.com/stretchr/testify/suite) was not adding much ([stretchr/testify/require](https://godoc.org/github.com/stretchr/testify/require) is still in use though)
- Add a check in the proxy for the number of replicas in the deployment. If there are 0 replicas, it holds the request without trying to do any network operations until the replica count goes up
    - This is done in preparation for #97 - we want the interceptor to be able to use this knowledge to push a prompt to KEDA to start the scaling operation

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] Have the interceptor watch the backing deployment and only send requests when they're at 1 or more replicas (when we get to #97, we can push to the scaler when we see a request come in and 0 replicas on the deployment)
- [x] Fix tests
- [x] Add more tests for the proxy handler
- [x] Make the operator start up the interceptor with the proper new env vars
- [x] Figure out the connection timeout tests (the ones that are failing right now)
- [x] Make the interceptor time out on the `waitFunc()` (see `newForwardingHandler`)

Fixes #61

### CODE REVIEW

**Comment by arschles** [comment]
@tomkerkhove @khaosdoctor @zroubalik this was a bigger change and one of the big blockers for releasing alpha 2. Can you PTAL?

**Review by khaosdoctor — APPROVED** [review]

**Comment by khaosdoctor** [comment]
I think that's fine, there's a test failing though.

**Review by zroubalik — APPROVED** [review]
LGTM, there's failing test though

**Comment by arschles** [comment]
Ok, tests fixed. Thanks for the reviews @khaosdoctor @zroubalik !

**Pull request merged**
