### PR TITLE
routing: lookup host without port

### LINKED ISSUE #608: Requests not routed when port specified on Host header
### Report

When requests are sent to the interceptor proxy with a port on the Host header, they are not routed and a 404 response is sent back to the user. This is the case if you want to test the HTTP Add-On locally and use `kubectl port-forward` to access the interceptor service.

### Expected Behavior

Just like other HTTP routing solutions, the port on the Host header should be ignored and requests routed regardless of the port value.

### Actual Behavior

Currently, the Host header needs to be an exact match of `.spec.host` for a request to be routed, so no requests with ports explicitly defined get routed.

### Steps to Reproduce the Problem

1. Create a HTTPScaledObject with `.spec.host` set to `localhost`
2. Run `kubectl port-forward -n keda svc/keda-add-ons-http-interceptor-proxy 8080`
3. Go to http://localhost:8080

### Logs from KEDA HTTP operator

N/A

### What version of the KEDA HTTP Add-on are you running?

0.4.0

### Kubernetes Version

1.24

### Platform

Microsoft Azure

### Anything else?

So we don't break compatibility for customers who may have defined the port on `.spec.host`, we can perform an exact match first and then try matching the Host header without the port section.

### PR DESCRIPTION
**Pull request by t0rr3sp3dr0**
Move from exact match for routing table host lookup to a domain-only match, ignoring ports.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] Any necessary documentation is added, such as:
  - [`README.md`](/README.md)
  - [The `docs/` directory](./docs)
  - [The docs repo](https://github.com/kedacore/keda-docs)

Fixes #608

### CODE REVIEW

**Comment by t0rr3sp3dr0** [comment]
@JorTurFer @tomkerkhove, would you be able to approve workflow runs for this PR?

**Comment by JorTurFer** [comment]
Approved the CI, I'll review this PR during the day! 
Thanks! ❤️

**Comment by t0rr3sp3dr0** [comment]
I think `Validate / validate - arm64 (pull_request)` is flaky. I've seen PRs that only contained doc changes and this test failed anyway. It's also failing on the master branch right now (https://github.com/kedacore/http-add-on/actions/runs/4236150711/jobs/7360624850).

**Comment by tomkerkhove** [comment]
Re-running

**Review by JorTurFer — APPROVED** [review]
LGTM!
Thanks for the contribution ❤️

**Pull request merged**
