### PR TITLE
reimplement custom interceptor metrics

### LINKED ISSUE #718: external-scaler spams log due to missing HTTPSO for dummy keda-add-ons-http-interceptor
### Report

The logs of the interceptor are spammed because keda-add-ons-http-interceptor only has a `ScaledObject` and no accompanying HTTPSO which the external-scaler tries to get

### Expected Behavior

This error should be ignored.

### Actual Behavior

The error is spamming the logs

### Steps to Reproduce the Problem

1. Install the keda-http-addon
2. Query the external-scaler logs

### Logs from KEDA HTTP operator

```
{"level":"error","ts":1687362513.545272,"logger":"GetMetricSpec","caller":"scaler/handlers.go:117","msg":"unable to get HTTPScaledObject","name":"keda-add-ons-http-interceptor","namespace":"keda","error":"httpscaledobject.http.keda.sh \"keda-add-ons-http-interceptor\" not found","stacktrace":"main.(*impl).GetMetricSpec\n\tgithub.com/kedacore/http-add-on/scaler/handlers.go:117\ngithub.com/kedacore/keda/v2/pkg/scalers/externalscaler._ExternalScaler_GetMetricSpec_Handler\n\tgithub.com/kedacore/keda/v2@v2.10.1-0.20230601160236-b5de66fe3857/pkg/scalers/externalscaler/externalscaler_grpc.pb.go:190\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\tgoogle.golang.org/grpc@v1.54.0/server.go:1345\ngoogle.golang.org/grpc.(*Server).handleStream\n\tgoogle.golang.org/grpc@v1.54.0/server.go:1722\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\tgoogle.golang.org/grpc@v1.54.0/server.go:966"}
```

### HTTP Add-on Version

0.5.0

### Kubernetes Version

1.25

### Platform

None

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by t0rr3sp3dr0**
Custom metrics for the Interceptor were mistakenly removed on #669. This patch reimplements this functionality and adds the missing ScaledObject for the Interceptor to the manifest directory.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] Any necessary documentation is added, such as:
  - [`README.md`](/README.md)
  - [The `docs/` directory](./docs)
  - [The docs repo](https://github.com/kedacore/keda-docs)

Related-to: kedacore/charts#487
Fixes: #718

### CODE REVIEW

**Review by JorTurFer — APPROVED** [review]

**Review by tomkerkhove — COMMENTED** [review]
Can we add some tests please?

**Comment by JorTurFer** [comment]
fuck, the auto-merge was enabled :( sorry

**Comment by t0rr3sp3dr0** [comment]
@tomkerkhove, do you mean more tests? I’ve added Interceptor-related tests to all 4 gRPC methods. https://github.com/kedacore/http-add-on/pull/720/files#diff-b0165c879226f6239e3bd158629f647c24a21b79aafba82b7b5df7e78a185c25

**Comment by nrukavkov** [comment]
the bug still with us. Version 0.5.3

**Comment by JorTurFer** [comment]
This PR hasn't been released yet. I think that we'll cut a release during this month

**Pull request merged**
