### PR TITLE
feat: allow skip scaled object creation with config

### PR DESCRIPTION
**Pull request by frankliu20**
When integrate Keda-Http with other KEDA scalers, we want to manage `ScaledObject` by ourselves, and add http-scaler as one of the triggers. In this PR, we allow users to do such `ScaledObject` management. When flag `SKIP_SCALED_OBJECT_CREATION` is set to `true`, keda-http-operator will skip the `ScaledObject` creation.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] Any necessary documentation is added, such as:
  - [`README.md`](/README.md)
  - [The `docs/` directory](./docs)
  - [The docs repo](https://github.com/kedacore/keda-docs)

### CODE REVIEW

**Comment by JorTurFer** [comment]
I think that this is a nice feature and simplifies the compatibility between KEDA and the HTTP add-on because avoid the requirement of implementing the whole ScaledObject spec in the add-on. WDYT @tomkerkhove  @t0rr3sp3dr0 ?

@frankliu20 , Could you add an [e2e test for testing this feature](https://github.com/kedacore/http-add-on/tree/main/tests)? IMO this requires [an update in docs](https://github.com/kedacore/http-add-on/tree/main/docs) to explain that this can be done for other users

**Comment by t0rr3sp3dr0** [comment]
I like the idea but would rather have this as a field in the HTTPSO definition instead of an Operator argument. That way, you could have some services using the managed SO while others use a custom one.

**Comment by JorTurFer** [comment]
@frankliu20 , any update?

**Comment by muecahit94** [comment]
Hi, any updates on that feature?

I would like to use zero scaling feature, but for that I need a combination of a keda built-in trigger and the http trigger, at the moment its not possible.

**Comment by JorTurFer** [comment]
It looks that the PR has been abandoned by the OP :( 
Are you willing to continue it @muecahit94 ?

**Comment by muecahit94** [comment]
@JorTurFer tbh no, just wanted to ask if there are any updates

**Comment by devopsdynamo** [comment]
I've opened up new PR to allow annotation to be set on the HTTPSO instead as this allows more flexibility.
https://github.com/kedacore/http-add-on/pull/929

**Comment by JorTurFer** [comment]
This feature is already done by https://github.com/kedacore/http-add-on/pull/929

**Pull request closed without merging**
