### PR TITLE
Scaling up the interceptor

### LINKED ISSUE #30: Scale up the interceptor
### Use-Case

When a lot of traffic comes in, the interceptor should scale up in addition to the app. This will require:

- A second trigger in the `ScaledObject`
- Another metric in the external scaler
- Possibly another queue endpoint on the interceptors (but I think the standard queue size should do it)

### Specification

- [ ] When more traffic enters the system, interceptors should scale up

### PR DESCRIPTION
**Pull request by arschles**
Scaling up the interceptor (along with the app pods) on high traffic events.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #30

### CODE REVIEW

**Comment by arschles** [comment]
@khaosdoctor @zroubalik @tomkerkhove can one or more of you PTAL?

**Comment by tomkerkhove** [comment]
I'll leave it up to the others

**Review by zroubalik — APPROVED** [review]
LGTM

**Comment by arschles** [comment]
@zroubalik @tomkerkhove thanks

**Pull request merged**
