### PR TITLE
feat: Use `registry.k8s.io/e2e-test-images/agnhost` instead of `arschles/xkcd`

### PR DESCRIPTION
**Pull request by JorTurFer**
Currently, we are using `arschles/xkcd` as docker image. This image isn't under our control and it doesn't support ARM64. As we support ARM64 arch.
As there is an image in Kubernetes registry for e2e tests which matches are requirements and it's multi arch, this PR replaces them

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes https://github.com/kedacore/http-add-on/issues/665

### CODE REVIEW

**Comment by t0rr3sp3dr0** [comment]
What about using `k8s.gcr.io/e2e-test-images/echoserver` instead? It would allow us to check much more on E2E, like that we are sending the proper URL and Headers to the application.

**Comment by t0rr3sp3dr0** [comment]
There's also the new `registry.k8s.io/e2e-test-images/agnhost:2.39`. It has a lot of different routes that return more structured data: https://github.com/kubernetes/kubernetes/blob/master/test/images/agnhost/netexec/netexec.go#L65.

**Comment by JorTurFer** [comment]
I didn't know about that, I'm going to take a look :heart:

**Comment by JorTurFer** [comment]
PTAL @t0rr3sp3dr0

**Review by t0rr3sp3dr0 — APPROVED** [review]
LGTM

**Pull request merged**
