### PR TITLE
Multi-tenant interceptor and scaler

### LINKED ISSUE #101: Provide support for scaling from 0 -> n and vice versa
Provide support for scaling from `0 -> n` and vice versa s that KEDA handles everything rather than just activation.

This should follow the KEDA core approach where it can create an HPA for the user or fully rely on external push.

### LINKED ISSUE #183: Economy of scale
From what I can see, for every new deployment that needs to be scaled down to zero, there are two _additional_ deployments that occur:

1. Interceptor
2. External scaler

As these deployments are not scaled down to zero and take resources from the cluster, the benefits of scale to zero are greatly reduced at best (if the user deployment takes equal or more resources than the interceptor and external scaler combined) or completely negated at worst (if the user deployment takes less resources than the interceptor and external scaler combined).

In addition, when the app is not scaled to zero, the interceptor and external scaler when deployed for every app will take resources from the cluster that could otherwise be used to schedule new deployments, and are sitting idle unless scale to zero occurs.

These insights rely on the design doc and my understanding of the code after a brief overview, so excuse misunderstandings.

/cc @tomkerkhove

### LINKED ISSUE #214: Not scaling to 0
## Expected Behavior
Scale to 0 when there is no traffic in the HTTP Request queue
## Actual Behavior
Always at a minimum of 1 replica
## Steps to Reproduce the Problem

I discussed with @arschles and @khaosdoctor about this problem and based on our investigations this behavior is caused by the following:

https://github.com/kedacore/http-add-on/blob/main/scaler/handlers.go#L33-L40

The `isActive` method here always returns `true`. Based on this bool KEDA scales to and from 0. If it true we scale from 0 to 1 and if its false the vice-versa.

### PR DESCRIPTION
**Pull request by arschles**
**This is a large PR that makes the interceptor and external scaler multi-tenant**.

See [below](https://github.com/kedacore/http-add-on/pull/206#issuecomment-900421289) for testing instructions.

Instead of starting up a single interceptor/scaler automatically _per application_, a fleet of interceptors/scalers run and can operate on any application in the same namespace. Interceptors can dynamically proxy requests based on the incoming request, scalers can dynamically report metrics on all applications, and the operator can provide routing information to the interceptor fleet. See https://hackmd.io/@arschles/mutitenant-keda-http-addon for more detailed design information.

In this pull request:

- The operator will not install any `Pod`s into the cluster when any `HTTPScaledObject` is created
- Any given interceptor pod can route a request to any installed application (in the same namespace)
- Interceptors are (still) horizontally scalable
- The operator maintains a "routing table" - a lookup table from hostname to the `Service`, Port`, and `Deployment` of a backing application
- Interceptor pods periodically request the updated routing table from the operator, and update their internal copy
- When the routing table is updated -- for example, when a new `HTTPScaledObject` is created -- the operator pings all interceptor pods to refresh their copy

There are several follow-ups to this PR, including but not limited to:

- https://github.com/kedacore/http-add-on/pull/247
- https://github.com/kedacore/http-add-on/pull/246
- #242

### Checklist

- [x] Update `design.md` and `walkthrough.md` in `docs/`directory
- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] Implement the routing table in the operator
- [x] Implement the routing table in the interceptor
- [x] Implement interceptor <--> operator RPC for the routing table
- [x] Remove code from operator that creates new resources
- [x] Make the routing table fetch path configurable in the operator
- [x] Expose metrics on the scaler so that KEDA can scale the interceptors as well
- [x] Clean up status values on the HTTPScaledObject
- [x] Make the external scaler respond based on the incoming `HTTPScaledObject`
    - requires that the queue knows about _all_ hosts
- [x] Fix & add tests:
    - [x] Add tests for the routing table in pkg/routing
    - [x] Add tests for the routing table pinger in the interceptor
    - [x] Add tests for the operator's routing table construction logic
    - [x] round trip tests for the routing table
    - [x] round trip tests for the HTTP request queue
    - [x] Fix broken tests
- [x] Make applicable updates to the helm chart in `kedacore/charts` (https://github.com/kedacore/charts/pull/169)
    - [x] Add or remove applicable fields from the CRD and update `kedacore/charts`. Some status fields will need removing, and a `host` field will need to be added so that the operator can build the routing table
    - [x] The helm chart needs to install the interceptor and scaler along with the operator
    - [x] add `ScaledObject` for interceptor. See above for details on work to make interceptor metrics available
- [x] Any necessary documentation is added, such as:
  - [`README.md`](/README.md)
  - [The `docs/` directory](./docs)
  - [The docs repo](https://github.com/kedacore/keda-docs)
- [x] e2e tests
- [x] any other unit/integration tests necessary
- [x] ensure that the scaler's `IsActive` method returns true _always_ for interceptors (so that they don't scale down to 0)
- [x] Change routing table communication strategy:
    - Operator records routing table to `ConfigMap`
    - Each interceptor fetches it on startup, records it to memory
    - Interceptors have an open watch stream on the map
    - Interceptors periodically fetch the `ConfigMap` (to ensure they converge to the correct table, even if they miss events)
- [x] Ensure that unnecessary configurations are removed from the associated helm chart

### Follow-Ups

- Verify that the routing table was updated in interceptors ([design](https://hackmd.io/YjJQRz5QQ_Wve5SnL1lYZQ?both#Verifying-that-the-routing-table-is-updated))
- Factor watch/list functionality out into a common abstraction (similar to, but simpler than informers): https://github.com/arschles/http-add-on/pull/13

---

Fixes #183
Fixes #214
Fixes #101

**NOTE: since this is a large pull request, we've split up the work.** To do so, we've created branches off of this branch and submitted PRs to this branch. Following are PRs that need to be merged into _into this branch_ before this should be reviewed and merged:
- [x] https://github.com/arschles/http-add-on/pull/10
    - [x] https://github.com/arschles/http-add-on/pull/11 should be merged into https://github.com/arschles/http-add-on/pull/10 before https://github.com/arschles/http-add-on/pull/10 is reviewed and merged

cc/ @yaron2 @tomkerkhove

### CODE REVIEW

**Comment by yaron2** [comment]
@arschles when do you think this will be ready for review?

**Comment by arschles** [comment]
@yaron2 this week sometime. I have to finish the routing table storage in the operator, then I can test it out, and from there I'll hit the button to make it not a draft PR. I'll `@` you at that point as well.

for context, I just moved to a new house 600 miles away over the weekend and am getting back on my feet 😆

**Comment by arschles** [comment]
@yaron2 an update here - everything is built at this point. I have an M1 Mac and having problems building images for amd64 architectures, so I am figuring that out and then I'll be ready to test in a cluster. Feel free to start reviewing this in the meantime if you like.

**Comment by yaron2** [comment]
> @yaron2 an update here - everything is built at this point. I have an M1 Mac and having problems (possibly qemu related) building images for amd64 architectures, so I am figuring that out and then I'll be ready to test in a cluster. Feel free to start reviewing this in the meantime if you like. The code is still rough, but it would be great to have more eyes on it sooner rather than later.

Roger Roger.

**Comment by khaosdoctor** [comment]
@arschles can you please add another to-do list item:

- [ ] Update charts on https://github.com/kedacore/charts/pull/169

**Comment by khaosdoctor** [comment]
I Will be responsible for the following:

- Change routing table communication strategy:
  - Operator records routing table to ConfigMap
  - Each interceptor fetches it on startup, records it to memory
  - Interceptors have an open watch stream on the map
  - Interceptors periodically fetch the ConfigMap (to ensure they converge to the correct table, even if they miss events)

**Comment by arschles** [comment]
>@arschles can you please add another to-do list item:


@khaosdoctor that TODO list item is in there but already checked off. would you like me to uncheck it?

**Comment by arschles** [comment]
>I Will be responsible for the following:

@khaosdoctor FYI I'm going to be working on adding e2e tests in this branch as well

**Comment by khaosdoctor** [comment]
> > @arschles can you please add another to-do list item:
> 
> @khaosdoctor that TODO list item is in there but already checked off. would you like me to uncheck it?

Oh haven't seen it! No worries, it's fine then :D

**Comment by khaosdoctor** [comment]
> > I Will be responsible for the following:
> 
> @khaosdoctor FYI I'm going to be working on adding e2e tests in this branch as well

Yep! I booked some time weekly starting next week to finish it ASAP

**Comment by arschles** [comment]
# How to test this

1. Ensure that KEDA is already installed 
1. Build the images in this PR using the following command: `mage dockerbuild dockerpush` (or if you want to use ACR Tasks: `mage dockerbuildacr`)
1. Check out the branch in this PR: https://github.com/kedacore/charts/pull/169
1. Install the chart from inside the `kedacore/charts` repo: `helm install http-add-on ./http-add-on -n $NAMESPACE --set images.tag=${TAG} --set images.operator=${OPERATOR_IMG} --set images.scaler=${SCALER_IMG} --set images.interceptor=${INTERCEPTOR_IMG}`
1. From inside this repository in this branch: `helm install xkcd ./examples/xkcd -n $NAMESPACE`
1. Now that the app is installed, you can issue requests to it. Use the `keda-add-ons-http-interceptor-proxy` `Service` on port 8080 for that. From inside the cluster in the same `$NAMESPACE`, do this: `curl -H "Host: myhost.com" keda-add-ons-http-interceptor-proxy:8080`
    - Note that you need the `Host` header so that the interceptor routes to the right place. To change that host, add this flag to the end of the `helm install xkcd` command: `--set host=<your host>`

**Review by yaron2 — APPROVED** [review]
lgtm

**Comment by yaron2** [comment]
Reviewed offline with @arschles, looks good.

**Review by tomkerkhove — APPROVED** [review]

**Comment by tomkerkhove** [comment]
Adding @zroubalik in case he wants to review as well

**Comment by tomkerkhove** [comment]
Oh OK, nvm - Auto-merge was on.

**Comment by benjaminhuo** [comment]
Huge improvement！

**Comment by zroubalik** [comment]
> Oh OK, nvm - Auto-merge was on.

🤣

**Review by zroubalik — COMMENTED** [review]
Looking good, though the PR is so huge, that I might have missed anything.
But I trust @arschles :) Great work!

**Comment by arschles** [comment]
thank you @tomkerkhove and @benjaminhuo 

@zroubalik sorry this got merged before you got a chance to look at it. if you'd like to review, please feel free to! I can make changes/fixes in follow-up PRs

**Comment by zroubalik** [comment]
@arschles no worries, I went through the code after the merge and it was looking good :)

**Comment by pkit** [comment]
Eh, unfortunately 2 pods per namespace still totally defeats the purpose of "multi-tenant scale to zero" as tenants usually l[ive in namespaces](https://kubernetes.io/blog/2021/04/15/three-tenancy-models-for-kubernetes/) and usually that's what is needed: scale each namespace to zero pods.

**Comment by arschles** [comment]
@pkit there needs to be at least one pod running, though, to handle incoming requests to applications that are scaled to zero. or am I missing something?

**Comment by benjaminhuo** [comment]
> @pkit there needs to be at least one pod running, though, to handle incoming requests to applications that are scaled to zero. or am I missing something?

In knative, the activator pod is just for this purpose which is always on

image

image

**Comment by pkit** [comment]
@arschles yup, 1 global deployment of request handlers is ok. But 1 per namespace is not that useful.
@benjaminhuo Knative solution looks good.

**Comment by arschles** [comment]
@benjaminhuo @pkit we've scoped the interceptor to an individual namespace on purpose, because KEDA is also scoped to a single namespace. We could expand the interceptor to be cluster-global, but doing so to gain better economies of scale would only make sense if the external scaler were made cluster-global as well. 

@yaron2 - you raised the issue that prompted this PR in the first place. WDYT?

Also, @tomkerkhove and @zroubalik WDYT as well?

**Comment by pkit** [comment]
@arschles my idea was to use something other than full fledged knative installation to just have that "scale-to-zero" feature.
But it seems like there is literally no other solution.
Thanks!

**Comment by arschles** [comment]
@pkit not sure what you mean?

**Comment by pkit** [comment]
@arschles there is no solution (other than knative) that provides "namespace scale to zero" functionality.

**Comment by tomkerkhove** [comment]
> @benjaminhuo @pkit we've scoped the interceptor to an individual namespace on purpose, because KEDA is also scoped to a single namespace. We could expand the interceptor to be cluster-global, but doing so to gain better economies of scale would only make sense if the external scaler were made cluster-global as well.
> 
> @yaron2 - you raised the issue that prompted this PR in the first place. WDYT?
> 
> Also, @tomkerkhove and @zroubalik WDYT as well?

Weren't we going to support both of the scenarios? I thought that was the case where you could have it cluster-wide if you want to centralize or have it namespaced if you want to isolate.

We do the same with KEDA where you can deploy it cluster-wide or scoped if you want to.

I think we should align, what are your thoughts @zroubalik @yaron2 ?

**Comment by arschles** [comment]
>@arschles there is no solution (other than knative) that provides "namespace scale to zero" functionality.

got it, thanks for clarifying. stay tuned, we might be adding that functionality soon (see https://github.com/kedacore/http-add-on/pull/206#issuecomment-923679547)

>Weren't we going to support both of the scenarios? I thought that was the case where you could have it cluster-wide if you want to centralize or have it namespaced if you want to isolate.

@tomkerkhove somebody [asked about that](https://github.com/kedacore/http-add-on/issues/240), but we didn't go all the way to making it cluster-global. we did, however, decide to allow interceptors/scalers/operators to run in any arbitrary namespace. making them cluster-global would be different work.

I wasn't aware that you could install KEDA at the cluster-wide level. can you point me to any docs on how to do that? I think if KEDA can be global, that makes it easier for the addon to do so as well.

**Comment by arschles** [comment]
👍 . Not sure how I didn't know this. I don't have the need to use KEDA across multiple namespaces much, I guess 😆 

I think, then, that https://github.com/kedacore/http-add-on/issues/240 can go on as planned. @pkit your wish from https://github.com/kedacore/http-add-on/pull/206#issuecomment-923200197 is going to be granted 😄

**Pull request merged**
