### PR TITLE
Adding configurability to the interceptor's HTTP round tripper

### LINKED ISSUE #248: Add configurability to the HTTP round tripper
The interceptor's HTTP round tripper has a few hard-coded values in its configuration:

```go
ForceAttemptHTTP2:     true,
MaxIdleConns:          100,
IdleConnTimeout:       90 * time.Second,
TLSHandshakeTimeout:   10 * time.Second,
ExpectContinueTimeout: 1 * time.Second,
```

These values should be made configurable, with the existing values as the defaults (except `ForceAttemptHTTP2` should default to false).

cc/ @yaron2 since we talked about this offline

### PR DESCRIPTION
**Pull request by arschles**
Removing hard-coded values in the http round tripper's configuration in the interceptor, and replacing them with values that can be set via environment variables in the interceptor

>This PR has been submitted as a draft because it relies on #206. It should not be reviewed or merged until that one it. It will be converted to a non-draft PR after that happens.
>
>**Update:** #206 is merged and this PR is taken out of draft mode. It is ready for review.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] Any necessary documentation is added, such as:
  - [`README.md`](/README.md)
  - [The `docs/` directory](./docs)
  - [The docs repo](https://github.com/kedacore/keda-docs)
- [x] Expose configs on helm chart

Fixes #248

cc/ @yaron2

### CODE REVIEW

**Comment by ajanth97** [comment]
Checked this. All good to be merged.

**Review by yaron2 — APPROVED** [review]
lgtm

**Review by ajanth97 — APPROVED** [review]
re-approving this.

**Comment by arschles** [comment]
Thanks @ajanth97

**Pull request merged**
