### PR TITLE
Magefiles

### LINKED ISSUE #42: Improve contrib experience with magefiles
Today there are a lot of makefiles to run scripts in the project, they're fine but take a while. The `docker-push-all` task runs all the builds sequentially while they could be running in parallel, this is just an example.

I propose to replace makefiles for [magefiles](https://magefile.org/) as @arschles pointed out in one of our discussions and port the scripts to these files. This will allow us to have a better handling of files and allow us to do more complex tasks in the dev environment.

> Plus, to improve contribex we can also version and ship the mage binary along with the repository to make the usage easier.

### PR DESCRIPTION
**Pull request by khaosdoctor**
Copy of #56

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] A PR is opened to update the documentation on [our docs repo](https://github.com/kedacore/keda-docs)

Fixes #42 
Closes #56

### CODE REVIEW

**Comment by khaosdoctor** [comment]
DCO is not identifying my signed commits here... I don't know why

**Comment by arschles** [comment]
@khaosdoctor looks like a commit you merged into this branch of mine has an anonymous GH email, which is causing the violation. You can probably manually amend that commit to fix

**Comment by khaosdoctor** [comment]
Can you point out the SHA of this commit? I can't find it here, all the ones I'm seeing are signed off.

**Comment by arschles** [comment]
It says this is the sha: https://github.com/kedacore/http-add-on/pull/79/commits/a89e73fd3c145e679effa63bbf12029df99026c4

Got it from [here](https://github.com/kedacore/http-add-on/pull/79/checks?check_run_id=2059982540)

**Pull request closed without merging**
