### PR TITLE
feat: Add ARM64 support

### PR DESCRIPTION
**Pull request by JorTurFer**
Signed-off-by: Jorge Turrado <jorge_turrado@hotmail.es>

This PR adds the necessary flows to generate ARM64 images in every push to main (`canary` tag) and also on every tag pushed to the repo. This PR also adds to e2e test the ARM execution on several k8s versions

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes https://github.com/kedacore/http-add-on/issues/364

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]
LGTM, thanks a ton!

**Comment by JorTurFer** [comment]
wow!
Thanks for reporting this because we are planning a new release (which would be wrong without this change).
I'm going to update this ASAP 🙇

**Comment by JorTurFer** [comment]
Thanks for reporting the issue @morganchristiansson 
[This PR](https://github.com/kedacore/http-add-on/pull/583) updates it to latest (I have tested it in my M1, and it works with prometheus operator correctly)

**Comment by morganchristiansson** [comment]
Excellent! Thank you for tagging a new release! My keda has in the past broken because it was left on canary image and new changes were merged.

**Pull request merged**
