### PR TITLE
Change images to scratch

### LINKED ISSUE #38: Change base docker image to scratch
The operator is using a distroless image, but the interceptor and the scaler are not. We should change the final base image to further reduce the image size

### PR DESCRIPTION
**Pull request by khaosdoctor**
_Update images on the interceptor and scaler to scratch to further reduce the size_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)

Fixes #38

### CODE REVIEW

**Comment by arschles** [comment]
This looks good. Going to wait until after alpha1 release (Friday) to merge it

**Review by arschles — COMMENTED** [review]
@khaosdoctor I trust you've tested this in a cluster?

**Comment by khaosdoctor** [comment]
Yep, I have tested it using our scripts in my AKS cluster

**Comment by khaosdoctor** [comment]
Just gave it a test run and it's working (with the errors from before #47)

**Review by arschles — APPROVED** [review]
Thanks @khaosdoctor

**Pull request merged**
