### PR TITLE
Add e2e test in build workflows

### PR DESCRIPTION
**Pull request by JorTurFer**
Signed-off-by: Jorge Turrado <jorge_turrado@hotmail.es>

As a first step to support ARM64, this PR adds another job after building the images that does a e2e test.
This extra job basically does these actions:
1. Install KEDA using helm
2. Install the http-add-on using helm with `canary/VERSION` tag
3. Install the sample using helm
4. Check that the SO generated based on the `HTTPScaledObject` is ready (`.status.Ready` == True)
5. Check that the workload has 0 instances
6. Do a request
7. Check that the workload has 1 instance

**Note:** Latest chart doesn't work with canary tag because right now, canary need an extra configuration that is [not merged and released with the chart yet](https://github.com/kedacore/charts/pull/251). You can check how it works [here](https://github.com/kedacore/http-add-on/runs/5779142389?check_suite_focus=true)

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] Any necessary documentation is added, such as:
  - [`README.md`](/README.md)
  - [The `docs/` directory](./docs)
  - [The docs repo](https://github.com/kedacore/keda-docs)

Related https://github.com/kedacore/http-add-on/issues/364

### CODE REVIEW

**Review by arschles — CHANGES_REQUESTED** [review]
@JorTurFer looks great! can you pull the scripts into separate files under a top-level `tests/` directory or something like that?

**Comment by JorTurFer** [comment]
Hey!
Sure, tomorrow I'll do it :)

**Comment by JorTurFer** [comment]
I'm working on it but probably the PR has to wait after Easter, I'm trying to add an e2e test also adding some http request to scale out (just for updating the topic)

**Comment by JorTurFer** [comment]
I have changed a bit the script to cover also a simple e2e test and not only the smoke test.
You can see it working in [this CI](https://github.com/kedacore/http-add-on/runs/5998638081?check_suite_focus=true) and failing (I have provocated a failure not scaling to the target value) in [this CI](https://github.com/kedacore/http-add-on/runs/5998672590?check_suite_focus=true)

**Review by arschles — APPROVED** [review]
@JorTurFer this looks good to me, thanks 👍

**Comment by JorTurFer** [comment]
The test is failing due to [this feature](https://github.com/kedacore/charts/pull/251) is needed in the chart (I wrote it in the PR description xD)

**Comment by v-shenoy** [comment]
@JorTurFer I was working on adding e2e and stress tests as a part of this - https://github.com/kedacore/http-add-on/issues/238 (Go-based, similar to keda core). But I see that you've added one here. What should I do then @JorTurFer ?

**Comment by JorTurFer** [comment]
> @JorTurFer I was working on adding e2e and stress tests as a part of this - https://github.com/kedacore/http-add-on/issues/238 (Go-based, similar to keda core). But I see that you've added one here. What should I do then @JorTurFer ?

If you are introducing e2e using go, go ahead 🙂. I did this several months ago as a pre step for supporting arm builds. My intention was having at least one "happy path", that's why I used bash but obviously, using golang is better :)

**Comment by JorTurFer** [comment]
In fact, current approach has strong dependency with the helm chart because I used it to simplify the deploy process and that's not the best IMO

**Pull request merged**
