### PR TITLE
Adding documentation for how to issue curl requests

### PR DESCRIPTION
**Pull request by arschles**
This PR adds instructions to the end of the `walkthrough.md` documentation that explain how to issue `curl` requests to your newly created application. Thanks to @iompo for the suggestion in https://github.com/kedacore/http-add-on/discussions/335#discussioncomment-1769458 to add this documentation

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] Any necessary documentation is added, such as:
  - [`README.md`](/README.md)
  - [The `docs/` directory](./docs)
  - [The docs repo](https://github.com/kedacore/keda-docs)

@iompo can you let me know if this documentation makes sense?

### CODE REVIEW

**Comment by iompo** [comment]
Hi @arschles, I think it does. 
By the way, I know it's not connected to your changes, but in the "_Creating an HTTPScaledObject_" section there's something missing in this sentence: "_This CRD object points the To get an example app up and running_".

**Review by tomkerkhove — APPROVED** [review]

**Comment by tomkerkhove** [comment]
> Hi @arschles, I think it does. By the way, I know it's not connected to your changes, but in the "_Creating an HTTPScaledObject_" section there's something missing in this sentence: "_This CRD object points the To get an example app up and running_".

Great remark @iompo, are you open to send a PR?

**Comment by iompo** [comment]
Hi @tomkerkhove, yes I can do that.

**Comment by iompo** [comment]
Hi @arschles, I just realized that, in the part of the doc you just added, there's one thing I did not fully understand: there's a note about the _Host_ header, you say that "_If you have a DNS name set up for the IP, you don't need this header_". Without that header how can the _keda-add-ons-http-interceptor-proxy_ know to what service redirect the request?

**Comment by arschles** [comment]
@iompo that is because the interceptor looks at both the `Host` header and the actual host in the incoming request URL. If you issue a request to `myhost.com`, the interceptor will detect the intended target app from the request URL's host

**Pull request merged**
